# -*- coding: utf-8 -*-
"""Supplementary morpheme dictionary (Continuum AE plugin Chinese patch).

Fills the gaps found by _work/words2.py: words that the older dict_zh /
dict_extra / dict_fix layers never covered, which is why strings like
"Match Move", "Alpha Blur" or "Advanced Controls" stayed in English.

Brand / format names that must stay Latin are mapped to themselves.
"""

MORE = {
    # ---------- 结构 / 分组标题 ----------
    "Shader": "着色器", "Surface": "表面", "Controls": "控制", "Control": "控制",
    "CONTROL": "控制", "Group": "分组", "Section": "分区", "Panel": "面板",
    "Advanced": "高级", "Common": "通用", "Main": "主", "Master": "主",
    "Stage": "舞台", "Scene": "场景", "World": "世界", "Local": "局部",
    "Global": "全局", "Overall": "整体", "General": "常规",

    # ---------- 选择器 / 工具 ----------
    "Chooser": "选取器", "Browser": "浏览器", "Launch": "启动", "Tool": "工具",
    "Tips": "提示", "Select": "选择", "Selected": "所选", "Pick": "拾取",
    "Load": "加载", "Save": "保存", "Update": "更新", "Apply": "应用",
    "Analyze": "分析", "Preview": "预览", "Compare": "比较", "Reset": "重置",

    # ---------- 三维 / 变形 ----------
    "Deformer": "变形器", "DEFORMER": "变形器", "Deflector": "导向板",
    "Geometry": "几何", "Vertex": "顶点", "Vertices": "顶点", "Face": "面",
    "Faces": "面", "Spline": "样条", "Curve": "曲线", "Curves": "曲线",
    "Bounded": "有界", "Infinite": "无限", "Plane": "平面", "Solid": "实体",
    "Reorient": "重定向", "Relief": "浮雕", "Extrude": "挤出", "Extruded": "挤出",
    "Bevel": "倒角", "Slant": "倾斜", "Shatter": "碎裂", "Warp": "扭曲",
    "Distort": "扭曲", "Bend": "弯曲", "Twist": "扭转", "Taper": "锥化",
    "Bulge": "凸出", "Pinch": "挤压", "Ripple": "涟漪", "Rippling": "波纹",
    "Wave": "波浪", "Turbulence": "湍流", "Fluid": "流体", "Fluids": "流体",
    "Dynamics": "动力学", "Cloth": "布料", "Bone": "骨骼", "Skin": "蒙皮",

    # ---------- 粒子 ----------
    "Particles": "粒子", "Particle": "粒子", "Emitter": "发射器",
    "Emitters": "发射器", "Emit": "发射", "Emission": "发射",
    "Attractor": "吸引点", "Attractors": "吸引点", "Force": "力",
    "Forces": "力", "Bounce": "弹跳", "Break": "断裂", "Connect": "连接",
    "Lifespan": "寿命", "Life": "生命周期", "Birth": "生成", "Death": "消亡",
    "Spawn": "生成", "Strands": "丝线", "Orb": "光球", "Orbs": "光球",

    # ---------- 跟踪 / 运动 ----------
    "Track": "跟踪", "Tracker": "跟踪器", "Tracking": "跟踪",
    "Stabilize": "稳定", "Stabilizer": "稳定器", "Corner": "边角",
    "Pins": "图钉", "Pin": "图钉", "Match": "匹配", "Move": "移动",
    "Motion": "运动", "Align": "对齐", "Interest": "注视点",
    "Transform": "变换", "Anchor": "锚点", "Registration": "注册",

    # ---------- 灯光 / 材质 ----------
    "Ambient": "环境", "Occlusion": "遮蔽", "Specular": "镜面",
    "Diffuse": "漫射", "Reflect": "反射", "Reflection": "反射",
    "Refraction": "折射", "Caustic": "焦散", "Caustics": "焦散",
    "Emissive": "自发光", "Transparency": "透明", "Subsurface": "次表面",
    "LIGHT": "灯光", "Built": "内置", "BUILT": "内置", "IN": "",
    "Sketch": "素描", "Art": "艺术", "Toon": "卡通", "Cartoon": "卡通",

    # ---------- 抠像 / 遮罩 ----------
    "Matte": "遮罩", "Spill": "溢色", "Choker": "收缩", "Cleaner": "清理",
    "Cleanup": "清理", "Colorize": "着色", "Linear": "线性",
    "Difference": "差值", "Mixed": "混合", "Chroma": "色度", "Luma": "亮度",
    "Premultiply": "预乘", "Premult": "预乘", "Conform": "适配",

    # ---------- 画质 / 处理 ----------
    "Downsampling": "下采样", "Upsampling": "上采样", "Convolution": "卷积",
    "Coarse": "粗略", "Fine": "精细", "Pass": "通道", "Calculation": "计算",
    "Method": "方法", "Quality": "质量", "Accuracy": "精度", "Tolerance": "容差",
    "Threshold": "阈值", "Smoothing": "平滑", "Sharpen": "锐化", "Sharpening": "锐化",
    "Denoise": "降噪", "Degrain": "去颗粒", "Deint": "去隔行",
    "Solarize": "中途曝光", "Posterize": "色调分离", "Halftone": "半色调",
    "Dither": "抖动", "Banding": "条带",

    # ---------- 时间 / 播放 ----------
    "Play": "播放", "Loop": "循环", "Looper": "循环器", "Retimer": "变速",
    "Duration": "时长", "Current": "当前", "Previous": "上一", "Next": "下一",
    "First": "首", "Last": "末", "Frame": "帧", "Frames": "帧",
    "Rate": "速率", "Speed": "速度", "Delay": "延迟", "Advance": "前进",

    # ---------- 通用形容词 ----------
    "Absolute": "绝对", "Relative": "相对", "Simple": "简单", "Free": "自由",
    "Double": "双重", "Multi": "多重", "Alternate": "交替", "Affected": "受影响",
    "Unexpected": "意外", "Warning": "警告", "Error": "错误", "Job": "任务",
    "Custom": "自定义", "Automatic": "自动", "Manual": "手动",
    "Enabled": "启用", "Disabled": "禁用", "Visible": "可见", "Hidden": "隐藏",
    "Locked": "锁定", "Unlocked": "解锁", "Solo": "单独",

    # ---------- 常用小词（多译为无，避免生硬） ----------
    "in": "", "on": "", "at": "", "to": "", "from": "从", "by": "", "of": "",
    "with": "", "and": "", "or": "", "for": "", "the": "", "a": "", "an": "",
    "per": "每", "Over": "随", "Under": "下方", "After": "之后", "Before": "之前",
    "Top": "顶", "Bot": "底", "Bottom": "底", "Cap": "端盖", "Bin": "分箱",
    "Gun": "喷枪", "Glue": "胶", "Mod": "调制",

    # ---------- 保留不译的品牌 / 格式 / 缩写 ----------
    "FEC": "FEC", "AE": "AE", "ML": "ML", "GPU": "GPU", "RT": "RT", "RP": "RP",
    "Adobe": "Adobe", "Avid": "Avid", "FCP": "FCP", "Resolve": "Resolve",
    "Filmora": "Filmora", "Edius": "Edius", "Mocha": "Mocha",
    "Archi": "Archi", "Grass": "草地", "Illusion": "Illusion",
    "Project": "项目", "Projects": "项目", "Presets": "预设", "Preset": "预设",
    "Continuum": "Continuum", "Systems": "系统", "System": "系统",
    "Collection": "集合", "Spectrum": "频谱", "Page": "页", "Turn": "翻页",
    "Overview": "概览", "Licensing": "授权", "Expression": "表达式",
    "Plugin": "插件", "Objects": "物体", "Object": "物体",
    "Artists": "艺术家", "Textured": "纹理", "Spatial": "空间",
    "Effects": "效果", "Effect": "效果", "Cross": "交叉",
    "Rectangular": "矩形", "Strands": "丝线", "Cleaner": "清理",
    "Preferences.bwsx": ".bwsx", "BCCInt": "BCCInt", "BCCTitle": "BCCTitle",
    "De": "去", "Obsolete": "旧版", "OBSOLETE": "旧版", "OBS": "旧版",
    "Vertex": "顶点", "Map": "贴图", "Generator": "生成器",
    "Contain": "包含", "Posted": "已发布", "Init": "初始化",
}

# Fixed phrases that read badly if composed word-by-word.
PHRASES = {
    "Match Move": "运动匹配",
    "Advanced Controls": "高级控制",
    "Advanced Gradient Controls": "高级渐变控制",
    "Alpha Blur": "阿尔法模糊",
    "Alpha Over Life": "生命周期阿尔法",
    "Alpha From Edges": "由边缘生成阿尔法",
    "Affect Fluids": "影响流体",
    "Affected By Fluids": "受流体影响",
    "Affected by Fluids": "受流体影响",
    "Align To Path Tag": "对齐到路径标签",
    "Align To Spline Tag": "对齐到样条标签",
    "Align to Motion": "对齐到运动",
    "Apply Pixel Chooser": "应用像素选取",
    "Apply Mode Spill": "应用模式溢色",
    "Apply Floor Rippling": "应用地面波纹",
    "Apply Reflect Rippling": "应用反射波纹",
    "Apply Tracking to": "应用跟踪到",
    "Ambient Occlusion Effect Shader": "环境遮蔽效果着色器",
    "Animation Tuning": "动画微调",
    "Apply Parameter": "应用参数",
    "AE 3D Layer Bounded": "AE三维图层有界",
    "AE 3D Layer Infinite": "AE三维图层无限",
    "AE 3D Layer with Alpha": "AE三维图层带阿尔法",
    "AE Mask": "AE遮罩",
    "Add Smoke/Fog": "添加烟雾",
    "Alternate Back": "交替背面",
    "Alternate FG Layer": "交替前景图层",
    "Alternate Front Faces": "交替正面",
    "Attached to Emitter": "附着到发射器",
    "Audio Apply Options": "音频应用选项",
    "Audio Spectrum Options": "音频频谱选项",
    "Bend Deformer Object": "弯曲变形器物体",
    "Bone Deformer Object": "骨骼变形器物体",
    "Bounce Over Life": "生命周期弹跳",
    "Bounce Variation": "弹跳变化",
    "Break on Deflector": "在导向板处断裂",
    "Break Particles": "断裂粒子",
    "Brick Surface Shader": "砖墙表面着色器",
    "Checkerboard Surface Shader": "棋盘表面着色器",
    "Coarse Pass": "粗略通道",
    "Fine Pass": "精细通道",
    "Color from Cleaned Alpha": "由清理后阿尔法取色",
    "Color Gun Offset": "喷枪颜色偏移",
    "Connect Free Emitters": "连接自由发射器",
    "Connect Particles": "连接粒子",
    "Connect to Main Emitter": "连接到主发射器",
    "Contain Destination Warp Shape": "包含目标扭曲形状",
    "Contain Source Warp Shape": "包含源扭曲形状",
    "Corner Pins": "边角图钉",
    "C.o.f.f.e.e. Expression Tag": "C.o.f.f.e.e.表达式标签",
    "Current Part": "当前部分",
    "Custom Orb Layer": "自定义光球图层",
    "Distort Blend Layer": "扭曲混合图层",
    "Double Click to Select Preset": "双击选择预设",
    "Edius Title Generator": "Edius字幕生成器",
    "Emission Angle": "发射角度",
    "Emit at Points": "在点处发射",
    "Emit From": "发射自",
    "Enable Fluid Dynamics": "启用流体动力学",
    "Enable Generator": "启用生成器",
    "Enable Tool Tips": "启用工具提示",
    "End Play Range": "播放结束范围",
    "Eyedropper Tool": "吸管工具",
    "FEC Simple Shadow": "FEC简单阴影",
    "FEC Simple Wire Removal": "FEC简单钢丝移除",
    "Fine Detail Radius": "精细细节半径",
    "Fix Expression Tag": "修复表达式标签",
    "Fluid Dy. Applied": "已应用流体动力学",
    "Generate from Alpha": "由阿尔法生成",
    "Grain Presets": "颗粒预设",
    "Image Collection - Flame": "图像集-火焰",
    "Image Collection - Particle": "图像集-粒子",
    "Illusion Project": "Illusion项目",
    "Layer CONTROL": "图层控制",
    "Launch Mocha": "启动Mocha",
    "Launch Mocha Track": "启动Mocha跟踪",
    "Load Animated Preset - Stretch": "加载动画预设-拉伸",
    "Load Animated Preset at First Frame": "在首帧加载动画预设",
    "Lock/Unlock Track": "锁定解锁跟踪",
    "Main Stage Project": "主舞台项目",
    "Max Downsampling": "最大下采样",
    "Better Downsampling": "更好下采样",
    "ML Warning Init Denoise Posted": "ML警告去噪初始化已发布",
    "ML Warning Init Retimer Posted": "ML警告变速初始化已发布",
    "None Selected": "未选择",
    "Opacity Under Reflect": "反射下不透明度",
    "Orb Custom Layer": "光球自定义图层",
    "Play": "播放",
    "Plugin Object": "插件物体",
    "Plugin Tag": "插件标签",
    "Registration Reminder Count": "注册提醒次数",
    "Registration Reminder Previous": "上次注册提醒",
    "Select Host Mask": "选择宿主遮罩",
    "Source Geometry": "源几何体",
    "Spatial Master": "空间主控",
    "Spectrum 14": "频谱14",
    "Unexpected Corrupt Tracker": "意外损坏的跟踪器",
    "Unexpected Missing Tracker": "意外缺失的跟踪器",
    "Update Alpha From Layer": "从图层更新阿尔法",
    "Update Color From Layer": "从图层更新颜色",
    "Use Old Calculation Method": "使用旧计算方法",
    "Use SIMD Convolution": "使用SIMD卷积",
    "Vertex Color Tag": "顶点颜色标签",
    "Vertex Map Shader Effect": "顶点贴着色器效果",
    "Wave Distort": "波浪扭曲",
    "Bot. Cap On": "底盖开启",
    "Top Cap On": "顶盖开启",
    "BUILT-IN CAMERA": "内置摄像机",
    "BUILT-IN LIGHT": "内置灯光",
    "Built-In Light": "内置灯光",
    "Built-in": "内置",
    "CURL DEFORMER": "卷曲变形器",
    "PULSE DEFORMER": "脉冲变形器",
    "ArchiCAD Tag": "ArchiCAD标签",
    "ArchiGrass Material": "ArchiGrass材质",
    "ArchiGrass Tag": "ArchiGrass标签",
    "Anchor Tag": "锚点标签",
    "Absolute": "绝对",
    "Acceleration": "加速度",
    "Analyze": "分析",
    "Appearance": "外观",
    "Attractors": "吸引点",
    "Attach Amount": "附着数量",
    "Background Effects": "背景效果",
    "Bin Frame Size": "分箱帧大小",
    "Bin View Mode": "分箱视图模式",
    "A Color": "颜色A",
    "A Height": "高度A",
    "Alt Back": "交替背面",
}
