# -*- coding: utf-8 -*-
"""Continuum 英->中 词素库（GBK 2字节/汉字）"""

TOKENS = {
    # ---- 通用 ----
    "Color": "颜色", "Colour": "颜色", "Colors": "颜色", "Color2": "颜色2",
    "Scale": "缩放", "Master": "主", "Size": "大小", "Amount": "数量",
    "Intensity": "强度", "Strength": "强度", "Opacity": "不透明度",
    "Position": "位置", "Pos": "位置", "Offset": "偏移", "Shift": "偏移",
    "Rotation": "旋转", "Rotate": "旋转", "Angle": "角度", "Spin": "自转",
    "Tumble": "翻滚", "Width": "宽度", "Height": "高度", "Length": "长度",
    "Radius": "半径", "Distance": "距离", "Depth": "深度", "Thickness": "厚度",
    "Speed": "速度", "Rate": "速率", "Frequency": "频率", "Time": "时间",
    "Frame": "帧", "Frames": "帧", "Duration": "时长", "Interval": "间隔",
    "Count": "数量", "Counts": "数量", "Num": "数量", "Number": "数量",
    "Random": "随机", "Randomness": "随机性", "Seed": "种子", "Noise": "噪波",
    "Jitter": "抖动", "Variance": "方差", "Variation": "变化", "Variations": "变化",
    "Softness": "柔和度", "Smooth": "平滑", "Smoothing": "平滑",
    "Smoothness": "平滑度", "Blur": "模糊", "Sharpen": "锐化", "Soften": "柔化",
    "Feather": "羽化", "Falloff": "衰减", "Fall": "衰减", "Fade": "淡出",
    "Mix": "混合", "Blend": "混合", "Blending": "混合", "Balance": "平衡",
    "Mode": "模式", "Type": "类型", "Enable": "启用", "Enabled": "启用",
    "On": "开", "Off": "关", "Use": "使用", "Using": "使用", "Invert": "反相",
    "Reverse": "反向", "In": "入", "Out": "出", "Inside": "内部",
    "Outside": "外部", "Top": "顶部", "Bottom": "底部", "Left": "左",
    "Right": "右", "Center": "中心", "Mid": "中间", "Midpoint": "中点",
    "Corner": "角", "Edge": "边缘", "Border": "边框", "Range": "范围",
    "Min": "最小", "Max": "最大", "Minimum": "最小", "Maximum": "最大",
    "Start": "开始", "End": "结束", "Pre": "前置", "Post": "后期",
    "Global": "全局", "Local": "局部", "Auto": "自动", "Manual": "手动",
    "Custom": "自定义", "Lock": "锁定", "Locked": "锁定", "Solo": "独显",
    "View": "视图", "Preview": "预览", "Output": "输出", "Input": "输入",
    "Source": "源", "Target": "目标", "Dest": "目标", "Destination": "目标",
    "Layer": "图层", "Channel": "通道", "Alpha": "阿尔法", "Matte": "遮罩",
    "Mask": "遮罩", "Clip": "裁剪", "Crop": "裁剪", "Choke": "收缩",
    "Spread": "扩散", "Grow": "扩张", "Wrap": "缠绕", "Stretch": "拉伸",
    "Direction": "方向", "Orientation": "朝向", "Pivot": "轴心",
    "Progress": "进度", "Trigger": "触发", "Loop": "循环", "Animation": "动画",
    "Motion": "运动", "Velocity": "速度", "Acceleration": "加速度",
    "Flow": "流动", "Wave": "波浪", "Ripple": "涟漪", "Twist": "扭曲",
    "Bend": "弯曲", "Warp": "扭曲", "Curl": "卷曲", "Displacement": "置换",
    "Disperse": "分散", "Dissolve": "溶解", "Morph": "变形", "Evolve": "演化",
    "Ratio": "比率", "Aspect": "纵横比", "Relative": "相对", "Absolute": "绝对",
    "Reference": "参考", "Status": "状态", "Reset": "重置", "Apply": "应用",
    "Adjust": "调整", "Correction": "校正", "Boost": "提升", "Level": "级别",
    "Levels": "色阶", "Order": "顺序", "Sequence": "序列", "Step": "步长",
    "Increment": "增量", "Spacing": "间距", "Density": "密度", "Detail": "细节",
    "Details": "细节", "Sharpness": "锐度", "Bias": "偏移", "Bias2": "偏移2",
    "Zoom": "缩放", "Pan": "平移", "Tilt": "倾斜", "Roll": "滚动",
    "Pivot": "轴心", "Anchor": "锚点", "Tracking": "跟踪", "Tracker": "跟踪器",
    "Stabilize": "稳定", "Stabilizer": "稳定器",

    # ---- 光 / 颜色 ----
    "Light": "灯光", "Lights": "灯光", "Lighting": "灯光", "Glow": "发光",
    "Glare": "眩光", "Flare": "光晕", "Glint": "闪烁", "Glitter": "闪光",
    "Shimmer": "微光", "Ray": "光线", "Rays": "光线", "Spot": "光斑",
    "Spotlight": "聚光灯", "SpotLight": "聚光灯", "Highlight": "高光",
    "Specular": "高光", "Shadow": "阴影", "Ambient": "环境", "Reflection": "反射",
    "Reflectivity": "反射率", "Refraction": "折射", "Attenuation": "衰减",
    "Brightness": "亮度", "Lightness": "明度", "Contrast": "对比度",
    "Saturation": "饱和度", "Hue": "色相", "Gamma": "伽马", "Tint": "色调",
    "Temperature": "色温", "Red": "红", "Green": "绿", "Blue": "蓝",
    "White": "白", "Black": "黑", "Gray": "灰", "Grey": "灰", "Luma": "亮度",
    "Chroma": "色度", "Chromatic": "色差", "Aberration": "色差", "Spill": "溢色",
    "Threshold": "阈值", "Key": "键控", "Keying": "键控", "Matte": "遮罩",

    # ---- 噪点 / 胶片 ----
    "Grain": "颗粒", "Film": "胶片", "Damage": "损伤", "Dirt": "脏点",
    "Scratch": "划痕", "Dust": "灰尘", "Vignette": "暗角", "Bloom": "泛光",
    "Streak": "条纹", "Stripe": "条纹", "Stripes": "条纹", "Line": "线",
    "Lines": "线", "Hair": "毛发", "Flicker": "闪烁", "Strobe": "频闪",
    "Pulse": "脉冲", "FlickerAmount": "闪烁量",

    # ---- 形状 / 几何 ----
    "Shape": "形状", "Circle": "圆", "Circular": "圆形", "Sphere": "球体",
    "Disc": "圆盘", "Disk": "圆盘", "Ring": "环", "Polygon": "多边形",
    "Point": "点", "Points": "点", "Pin": "图钉", "Path": "路径",
    "Curve": "曲线", "Graph": "曲线", "Bezier": "贝塞尔", "Spline": "样条",
    "Box": "盒", "Cube": "立方", "Cylinder": "圆柱", "Plane": "平面",
    "Grid": "网格", "Block": "块", "Brick": "砖", "Tile": "平铺",
    "Pattern": "图案", "Texture": "纹理", "Map": "贴图", "Bump": "凹凸",
    "Normal": "法线", "Fractal": "分形", "Octave": "倍频", "Turbulence": "湍流",

    # ---- 合成 / 风格 ----
    "Composite": "合成", "Blend": "混合", "Overlap": "重叠", "Gradient": "渐变",
    "Posterize": "色调分离", "Cartoon": "卡通", "Toon": "卡通", "Sketch": "素描",
    "Paint": "绘制", "Stroke": "描边", "Glow": "发光", "Edge": "边缘",
    "Outline": "轮廓", "Silhouette": "剪影", "Hollow": "空心", "Solid": "实心",
    "Fill": "填充", "Background": "背景", "Foreground": "前景",
    "Wipe": "擦除", "Transition": "转场", "Dissolve": "溶解",

    # ---- 摄像机 / 3D ----
    "Camera": "摄像机", "Cam": "摄像机", "Lens": "镜头", "Focus": "焦点",
    "Aperture": "光圈", "Iris": "光圈", "Exposure": "曝光", "Zoom": "变焦",
    "Orbit": "轨道", "Dolly": "推拉", "Perspective": "透视", "Projection": "投影",
    "Extruded": "挤出", "Bevel": "倒角", "Lathe": "车削", "EPS": "EPS",

    # ---- 文字 ----
    "Text": "文字", "Type-On": "打字机", "Type": "打字", "Titler": "字幕",
    "Title": "标题", "Font": "字体", "Character": "字符", "Word": "词",
    "Line": "行", "Paragraph": "段落", "Kerning": "字距", "Leading": "行距",
    "Justify": "对齐", "Align": "对齐", "Baseline": "基线",

    # ---- 前缀 / 缩写 ----
    "BG": "背景", "FG": "前景", "PC": "像素选区", "FX": "特效",
    "L1": "L1", "L2": "L2", "L3": "L3", "L4": "L4",
    "X": "X", "Y": "Y", "Z": "Z", "XY": "XY", "W": "W", "H": "H",
    "A": "A", "B": "B", "R": "红", "G": "绿", "C": "C", "M": "洋红",
    "UV": "UV", "RGB": "RGB", "RGBA": "RGBA", "HSL": "HSL",

    # ---- 连接词 / 单位（尽量不占位） ----
    "to": "", "of": "", "for": "", "and": "", "the": "", "with": "",
    "(": "", ")": "", "%": "%", "(%)": "%", "(sec)": "秒", "(secs)": "秒",
    "(degrees)": "度", "-": "",

    # ---- 效果名专用 ----
    "Ambient": "环境", "Atmospheric": "大气", "Audio": "音频",
    "Visualizer": "可视化", "Beauty": "美颜", "Studio": "工作台",
    "Bleach": "漂白", "Bypass": "绕过", "Borders": "边框", "Bulge": "凸出",
    "Caustics": "焦散", "Cine": "电影", "Style": "风格", "Grunge": "做旧",
    "Leaks": "漏光", "Titler": "字幕", "Witness": "证人",
    "Protection": "保护", "Warp": "扭曲", "Z-Space": "Z空间",
    "Primatte": "Primatte", "Mokey": "Mokey", "Mocha": "Mocha",
    "Optical": "光学", "Stabilizer": "稳定器", "UpRez": "升采样",
    "Remover": "移除", "Removal": "移除", "Object": "物体",
    "Corner": "角", "Pinning": "钉住", "Blobbylize": "融化",
    "Cloner": "克隆", "Damaged": "破损", "Deinterlace": "去隔行",
    "DeNoise": "降噪", "Drop": "投影", "Emboss": "浮雕", "Extruder": "挤出",
    "Fast": "快速", "Flipper": "翻转", "Fog": "雾", "Fractal": "分形",
    "Freeze": "冻结", "Glow": "发光", "Gradients": "渐变", "Halftone": "半调",
    "Hue": "色相", "Infrared": "红外", "Jitter": "抖动", "Lens": "镜头",
    "Light": "光", "Lighting": "灯光", "Looks": "影调", "Median": "中值",
    "Mirrors": "镜像", "Mosaic": "马赛克", "Multitone": "多色调",
    "Night": "夜景", "Noise": "噪点", "Organic": "有机", "Particle": "粒子",
    "Posterize": "色调分离", "Puffy": "膨胀", "Rain": "雨", "Rays": "光线",
    "Raster": "栅格", "ReLight": "重打光", "Scanline": "扫描线",
    "Sequencer": "序列器", "Shadows": "阴影", "Shear": "切变",
    "Silhouette": "剪影", "Sketch": "素描", "Skew": "斜切", "Smear": "涂抹",
    "Snow": "雪", "Sparkle": "闪烁", "Streaks": "条纹", "Super": "超级",
    "Swish": "甩尾", "Swirl": "漩涡", "Terrain": "地形", "Threshold": "阈值",
    "Threads": "线", "Tiler": "平铺", "Tint": "色调", "Trails": "拖尾",
    "Turbulence": "湍流", "Twister": "扭转", "Unsharp": "非锐化",
    "Vector": "矢量", "Velocity": "速度", "Vignette": "暗角",
    "Water": "水", "Waves": "波浪", "Wide": "宽", "Wind": "风",
    "Wireframe": "线框", "Wood": "木纹", "Zenith": "天顶",
    "BCC+": "", "BCC": "", "OBSOLETE": "旧版", "Plus": "加强",
    "Advanced": "高级", "Artist": "艺术", "Bad": "坏", "Beat": "节拍",
    "Reactor": "反应器", "Broadcast": "广播", "Safe": "安全",
    "Cartooner": "卡通", "Chroma": "色度", "Key": "键控", "Studio": "工作室",
    "Film": "胶片", "Glow": "发光", "Dam": "损伤", "Grade": "调色",
    "Levels": "色阶", "Match": "匹配", "Three": "三", "Way": "路",
    "Split": "分割", "Tone": "色调", "Vignette": "暗角",
}

# 整条效果名的手工覆盖（组合不好的走这里）
EFFECT_OVERRIDE = {
    "BCC 3 Way Color Grade": "三级调色",
    "BCC 3D Image Shatter": "三维图像碎裂",
    "BCC Beauty Studio": "美颜工作室",
    "BCC Bleach Bypass": "漂白 bypass",
    "BCC Blur Dissolve": "模糊溶解",
    "BCC Beat Reactor": "节拍反应器",
    "BCC Chroma Key": "色度键控",
    "BCC Film Glow": "胶片光晕",
    "BCC Film Damage": "胶片损伤",
    "BCC Grunge": "做旧",
    "BCC Lens Flare": "镜头光晕",
    "BCC Light Leaks": "漏光",
    "BCC Light Rays": "光线",
    "BCC Optical Stabilizer": "光学防抖",
    "BCC Titler Studio": "字幕工作室",
    "BCC Type-On Text": "打字机文字",
    "BCC Witness Protection": "马赛克遮挡",
    "BCC Vignette": "暗角",
    "BCC Z-Space 1": "Z空间1",
    "BCC Z-Space 2": "Z空间2",
    "BCC Primatte Studio": "Primatte 抠像",
    "BCC UpRez": "分辨率提升",
    "BCC DeNoise": "降噪",
    "BCC Deinterlace": "去隔行",
    "BCC Drop Shadow": "投影",
    "BCC Fast Flipper": "快速翻转",
    "BCC Fog": "雾",
    "BCC Freeze Frame": "冻结帧",
    "BCC Halftone": "半调",
    "BCC Infrared": "红外",
    "BCC Jitter": "抖动",
    "BCC Median": "中值",
    "BCC Mosaic": "马赛克",
    "BCC Multitone": "多色调",
    "BCC Night Vision": "夜视",
    "BCC Posterize": "色调分离",
    "BCC Rain": "雨",
    "BCC Raster": "栅格",
    "BCC ReLight": "重新打光",
    "BCC Scanline": "扫描线",
    "BCC Sequencer": "序列器",
    "BCC Shear": "切变",
    "BCC Skew": "斜切",
    "BCC Smear": "涂抹",
    "BCC Snow": "雪",
    "BCC Sparkle": "闪烁",
    "BCC Super Blur": "超级模糊",
    "BCC Swish Pan": "甩镜",
    "BCC Swirl": "漩涡",
    "BCC Terrain": "地形",
    "BCC Threads": "线纹",
    "BCC Tiler": "平铺",
    "BCC Twister": "扭转",
    "BCC Unsharp Mask": "非锐化遮罩",
    "BCC Vector Blur": "矢量模糊",
    "BCC Velocity Remap": "速度重映射",
    "BCC Water Waves": "水波",
    "BCC Wide Angle Lens": "广角镜头",
    "BCC Wind": "风",
    "BCC Wireframe": "线框",
    "BCC Wood Grain": "木纹",
    "BCC Zenith": "天顶",
}
