# -*- coding: utf-8 -*-
"""补充词素（覆盖未登录词高频部分）"""

EXTRA = {
    # 连接词（不占位）
    "To": "", "From": "", "At": "", "at": "", "With": "", "with": "",
    "In": "入", "Out": "出", "Over": "叠", "Under": "下", "After": "后",
    "Before": "前", "Only": "仅", "All": "全部", "Single": "单",
    "Two": "双", "One": "单", "Whole": "整体", "Per": "每", "By": "按",

    # 高频未登录词
    "Ease": "缓动", "Modulation": "调制", "Insert": "插入", "Attractor": "吸引点",
    "Fire": "火焰", "Sampler": "采样器", "Peak": "峰值", "Feedback": "反馈",
    "Area": "区域", "ChromaHoop": "色环", "ChromaFan": "色扇", "Chromafan": "色扇",
    "Bot": "下", "Inherit": "继承", "Separation": "分离", "Taffy": "拉丝",
    "Scramble": "打乱", "Egg": "蛋", "Shake": "抖动", "Add": "添加",
    "Filter": "滤镜", "Effect": "效果", "Ribbon": "带状", "Amplitude": "振幅",
    "Move": "移动", "Back": "背面", "File": "文件", "Sub": "子",
    "Dye": "染色", "Phase": "相位", "Field": "场", "Elevation": "仰角",
    "Midtone": "中间调", "Incoming": "入射", "Sys": "系统", "Mirror": "镜像",
    "Mutation": "变异", "Outgoing": "出射", "Stain": "污渍", "Skip": "跳过",
    "Alternate": "交替", "Bi": "双向", "Reduction": "减少", "Feathering": "羽化",
    "Options": "选项", "Discs": "圆盘", "Image": "图像", "Resolution": "分辨率",
    "Preserve": "保留", "Hollows": "空洞", "Taper": "锥化", "Letter": "字母",
    "System": "系统", "Sample": "采样", "Smoke": "烟", "Reveal": "显现",
    "Twirl": "扭转", "Completion": "完成", "Weight": "权重", "Var": "变量",
    "Burn": "烧焦", "Freq": "频率", "Clone": "克隆", "Cloud": "云",
    "Boundary": "边界", "Control": "控制", "Core": "核心", "Diffuse": "漫反射",
    "Displace": "置换", "Sink": "下沉", "Extrusion": "挤出", "Tolerance": "容差",
    "Rolling": "滚动", "Hilight": "高光", "Horizontal": "水平", "Influence": "影响",
    "Spots": "斑点", "Rot": "旋转", "Obscuration": "遮挡", "Rad": "半径",
    "Rivet": "铆钉", "Show": "显示", "Sweep": "扫掠", "Timing": "时序",
    "Man": "人", "Transform": "变换", "Vein": "叶脉", "Vertical": "垂直",
    "World": "世界", "Adjustment": "调整", "Sampling": "采样", "Delta": "增量",
    "Angular": "角度", "sec": "秒", "Directional": "方向性", "Scheme": "方案",
    "Run": "运行", "Sat": "饱和度", "Gravity": "重力", "Chaos": "混沌",
    "Distortion": "畸变", "Movement": "移动", "Complexity": "复杂度",
    "Cone": "锥体", "Expand": "扩展", "Percent": "百分比", "Suppression": "抑制",
    "Draw": "绘制", "Low": "低", "High": "高", "Edges": "边缘",
    "Limit": "限制", "Far": "远", "Near": "近", "Flip": "翻转",
    "Floor": "地面", "Front": "前面", "Ghost": "重影", "Glitch": "故障",
    "Ground": "地面", "Horiz": "水平", "Individual": "单独", "Inner": "内部",
    "Iterations": "迭代", "Keyframe": "关键帧", "LED": "LED", "Legacy": "旧版",
    "Life": "寿命", "Lum": "亮度", "Magenta": "洋红", "Vert": "垂直",
    "Radial": "径向", "Middle": "中间", "Location": "位置", "Overlay": "叠加",
    "Quality": "质量", "Outer": "外部", "Region": "区域", "Overall": "整体",
    "Transfer": "转移", "PixelChooser": "像素选区", "Process": "处理",
    "Randomize": "随机化", "Remap": "重映射", "Render": "渲染",
    "Container": "容器", "Multiplier": "倍数", "Side": "侧", "Spark": "火花",
    "Replace": "替换", "Splash": "飞溅", "Star": "星", "String": "字符串",
    "Thread": "线", "Turb": "湍流", "Evolution": "演化", "Wedge": "楔形",
    "Percentage": "百分比", "Cutoff": "截止", "Follow": "跟随", "Power": "强度",
    "Transparent": "透明", "Base": "基础", "Bass": "低音", "Preset": "预设",
    "Delay": "延迟", "Samples": "采样数", "Transparency": "透明度",
    "Extra": "额外", "Bouncing": "弹跳", "Coarseness": "粗糙度", "Clamp": "钳制",
    "Casts": "投射", "Cb": "Cb", "Cr": "Cr", "Channels": "通道",
    "Char": "字符", "Choice": "选择", "Matching": "匹配", "Compositing": "合成",
    "Contract": "收缩", "Roundness": "圆度", "Decay": "衰减", "Degraded": "退化",
    "Diff": "差异", "Diffraction": "衍射", "Dispersion": "色散", "Display": "显示",
    "Distorted": "扭曲", "Sensitivity": "灵敏度", "Operation": "运算",
    "Ellipse": "椭圆", "Ending": "结束", "Explosion": "爆炸", "Amt": "量",
    "Flap": "摆动", "Flash": "闪光", "Group": "组", "Floating": "浮动",
    "Footage": "素材", "Galaxy": "星系", "Compensation": "补偿", "Mist": "薄雾",
    "Hold": "保持", "Horizon": "地平线", "Host": "宿主", "Hybrid": "混合",
    "Format": "格式", "Lift": "提升", "Gain": "增益", "Interpolation": "插值",
    "Inverse": "反向", "Squeeze": "挤压", "Maps": "贴图", "Cleanup": "清理",
    "Hz": "赫兹", "Lifetime": "生命周期", "Deviation": "偏差", "Midtones": "中间调",
    "Misalignment": "错位", "Monitor": "监视器", "Mortar": "砂浆", "Affects": "影响",
    "Normalize": "归一化", "Opaque": "不透明", "Orbs": "光球",
    "Overdrive": "过冲", "Perpendicular": "垂直", "Perturbation": "扰动",
    "Result": "结果", "Spiral": "螺旋", "Rhythm": "节奏", "Screen": "屏幕",
    "Large": "大", "Medium": "中", "Small": "小", "Sky": "天空",
    "Starting": "起始", "Static": "静态", "Suppress": "抑制", "Temporal": "时域",
    "Gap": "间隙", "Jump": "跳跃", "Comp": "合成", "Vary": "变化",
    "Warm": "暖", "Cool": "冷", "Wiggle": "摆动", "Gust": "阵风",
    "Impulse": "脉冲", "Action": "动作", "Alignment": "对齐", "Subtlety": "细微",
    "Anti": "抗", "Aliasing": "锯齿", "Antialiased": "抗锯齿",
    "Antialiasing": "抗锯齿", "Geometrics": "几何", "When": "当",
    "Animate": "动画", "Steps": "步数", "Orient": "朝向", "Average": "平均",
    "Axial": "轴向", "Axis": "轴", "Birth": "生成", "Birthrate": "生成率",
    "Blurriness": "模糊度", "Bokeh": "散景", "Corners": "角",
    "Breaking": "断裂", "Bulb": "灯泡", "Bunching": "成束", "Burst": "爆发",
    "Calibration": "校准", "Model": "模型", "Cellularity": "细胞状",
    "Checkbox": "复选框", "Choose": "选择", "Fan": "扇", "Hoop": "环",
    "Cycle": "循环", "Cleaning": "清洁", "Clipping": "裁剪", "Cyan": "青",
    "Deflicker": "去闪烁", "Disappearing": "消失", "Dissolve": "溶解",
    "Distribution": "分布", "Draft": "草稿", "Drawing": "绘制",
    "Jaggedness": "锯齿度", "Padding": "填充", "Shapes": "形状",
    "Emitter": "发射器", "Enhance": "增强", "Erosion": "侵蚀", "Extend": "延伸",
    "Faces": "面", "Faded": "淡化", "Focal": "焦距", "Framing": "构图",
    "Gel": "色片", "Generation": "生成", "Glittering": "闪烁",
    "Desaturation": "去饱和", "Glows": "发光", "Gradation": "层次", "Grit": "砂砾",
    "Harden": "硬化", "Histogram": "直方图", "Ignore": "忽略", "Pixels": "像素",
    "Illumination": "照明", "Inertia": "惯性", "Init": "初始", "Inset": "内缩",
    "Interference": "干涉", "Interpret": "解释", "Curvature": "曲率",
    "Keep": "保持", "Marker": "标记", "Function": "函数", "Behavior": "行为",
    "Lightning": "闪电", "Link": "链接", "Logging": "日志", "Long": "长",
    "Look": "外观", "Lower": "下限", "Upper": "上限", "Maintain": "维持",
    "Make": "生成", "Material": "材质", "Choker": "收缩", "Refinement": "细化",
    "Metallic": "金属", "Method": "方法", "MixBack": "混合回", "Behind": "后方",
    "Original": "原始", "Monochrome": "单色", "Monochromatic": "单色",
    "Oscillation": "振荡", "Pan": "平移", "Paper": "纸张", "Physics": "物理",
    "Pinch": "收缩", "Pixelate": "像素化", "Plate": "板", "Positioning": "定位",
    "Polarize": "偏振", "Sides": "面", "Polygons": "多边形", "Scaling": "缩放",
    "Scan": "扫描", "Scatter": "散开", "Scratches": "划痕", "Search": "搜索",
    "Setup": "设置", "Shatter": "碎裂", "Shininess": "光泽", "Short": "短",
    "Shrink": "收缩", "Shutter": "快门", "Signal": "信号", "Similarity": "相似度",
    "Slide": "滑动", "Span": "跨度", "Spawn": "生成", "Deceleration": "减速",
    "Dist": "距离", "Squareness": "方形度", "Stick": "粘附", "Strike": "打击",
    "Stringiness": "丝状", "Symmetrical": "对称", "Temp": "临时", "Test": "测试",
    "Textures": "纹理", "Thicken": "加厚", "Thin": "细", "Tiling": "平铺",
    "Window": "窗口", "Tip": "尖端", "Trail": "拖尾", "Transforms": "变换",
    "Translation": "平移", "Transmission": "透射", "Treble": "高音",
    "Triangle": "三角", "Twinkle": "闪烁", "Undistort": "去畸变", "Units": "单位",
    "Warpers": "扭曲器", "Viewer": "查看器", "Waveform": "波形",
    "Wavelength": "波长", "Waviness": "波浪度", "Weave": "编织",
    "Wiggliness": "摆动", "Wiggly": "摆动", "Wispiness": "丝状",
    "Workflow": "工作流", "Wrapping": "包裹", "Yellow": "黄",
    "Cache": "缓存", "Toolbar": "工具栏", "Indicators": "指示器",
    "Estimation": "估算", "Intersection": "相交", "History": "历史",
    "Trackers": "跟踪器", "Mipmaps": "Mipmap", "Layers": "图层",
    "Colored": "着色", "OpenFX": "OpenFX", "Restrictions": "限制",
    "Cache": "缓存", "Factor": "系数", "Up": "上", "Down": "下",
    "Prism": "棱镜", "Pulldown": "下拉", "Push": "推", "Quick": "快速",
    "Red": "红", "Reduce": "减少", "Reflections": "反射", "Repeats": "重复",
    "Replacement": "替换", "Resample": "重采样", "Rings": "环",
    "Slow": "慢", "Sound": "声音",

    # 复合方位
    "Top-Left": "左上", "Top-Right": "右上", "Bot-Left": "左下",
    "Bot-Right": "右下", "Top": "顶部", "Left": "左", "Right": "右",
    "Bottom": "底部", "SW": "西南", "NE": "东北", "NW": "西北", "SE": "东南",
    "TL": "左上", "TR": "右上", "BL": "左下", "BR": "右下",
    "HT": "高", "LT": "低", "CL": "色差", "HV": "水平垂直",
}
