# -*- coding: utf-8 -*-
"""生成 Inno Setup 脚本（.iss）—— 备份原版 + 安装中文 + 可还原"""
import os

WORK = r"D:\Programming project\插件汉化\_work"
PKG = r"D:\Programming project\插件汉化\Continuum 汉化组件 v19.0.0"
LIB = r"C:\Program Files\BorisFX\ContinuumAE\19\lib"
CONT = r"C:\Program Files\Adobe\Common\Plug-ins\7.0\MediaCore\BorisFX\Continuum"

aex_dir = os.path.join(PKG, 'aex')
dll_dir = os.path.join(PKG, 'dll')
aex_files = sorted(f for f in os.listdir(aex_dir) if f.lower().endswith('.aex'))
dll_files = sorted(f for f in os.listdir(dll_dir) if f.lower().endswith('.dll'))

L = []
L.append("; Continuum 2026 Chinese patch  (generated)")
L.append("")
L.append("[Setup]")
L.append("AppName=Continuum 2026 Hanhua")
L.append("AppVersion=19.0.0")
L.append("AppPublisher=BorisFX Continuum Chinese Patch")
L.append("DefaultDirName={commonpf}\\BorisFX\\ContinuumAE\\19")
L.append("DisableDirPage=yes")
L.append("DisableProgramGroupPage=yes")
L.append("DisableReadyPage=yes")
L.append("OutputBaseFilename=ContinuumHanhua_v19.0.0")
L.append("OutputDir=.")
L.append("Compression=lzma2/ultra64")
L.append("SolidCompression=yes")
L.append("PrivilegesRequired=admin")
L.append("PrivilegesRequiredOverridesAllowed=dialog")
L.append("Uninstallable=yes")
L.append("UninstallDisplayName=Continuum 2026 Hanhua (v19.0.0)")
L.append("WizardStyle=modern")
L.append("ArchitecturesAllowed=x64")
L.append("")
L.append("[Languages]")
L.append('Name: "english"; MessagesFile: "compiler:Default.isl"')
L.append("")
L.append("[Files]")
for f in dll_files:
    dest = "{pf}\\BorisFX\\ContinuumAE\\19\\lib" if f != 'BCCPlus.dll' \
        else "{pf}\\Adobe\\Common\\Plug-ins\\7.0\\MediaCore\\BorisFX\\Continuum"
    L.append(f'Source: "dll\\{f}"; DestDir: "{dest}"; Flags: ignoreversion uninsneveruninstall')
L.append('Source: "aex\\*"; DestDir: "{pf}\\Adobe\\Common\\Plug-ins\\7.0\\MediaCore\\BorisFX\\Continuum"; '
         'Flags: ignoreversion uninsneveruninstall')
L.append('Source: "Restore-English.bat"; DestDir: "{app}\\Hanhua"; Flags: ignoreversion')
L.append('Source: "说明.txt"; DestDir: "{app}\\Hanhua"; Flags: ignoreversion')
L.append('Source: "效果名对照表.txt"; DestDir: "{app}\\Hanhua"; Flags: ignoreversion')
L.append('Source: "参数名对照表.txt"; DestDir: "{app}\\Hanhua"; Flags: ignoreversion')
L.append("")
L.append("[Code]")
L.append("")
L.append("const")
L.append("  CONT = 'C:\\Program Files\\Adobe\\Common\\Plug-ins\\7.0\\MediaCore\\BorisFX\\Continuum';")
L.append("  LIBD = 'C:\\Program Files\\BorisFX\\ContinuumAE\\19\\lib';")
L.append("")
L.append("function BackupOne(src, bak: String): Boolean;")
L.append("begin")
L.append("  Result := True;")
L.append("  if not FileExists(src) then exit;")
L.append("  if FileExists(bak) then exit;")
L.append("  Result := FileCopy(src, bak, False);")
L.append("end;")
L.append("")
L.append("function PrepareToInstall(var NeedsRestart: Boolean): String;")
L.append("var")
L.append("  tmp, outp: String;")
L.append("  rc: Integer;")
L.append("begin")
L.append("  Result := '';")
L.append("")
L.append("  // 1) AE 必须在关闭状态")
L.append("  tmp := ExpandConstant('{tmp}\\procs.txt');")
L.append("  if Exec('cmd.exe', '/C tasklist /NH > \"' + tmp + '\"', '', SW_HIDE,")
L.append("         ewWaitUntilTerminated, rc) then begin")
L.append("    if LoadStringFromFile(tmp, outp) then begin")
L.append("      if Pos('AfterFX.exe', outp) > 0 then begin")
L.append("        Result := 'After Effects is running.' + #13#10 +")
L.append("                  'Please quit After Effects completely, then run this installer again.';")
L.append("        exit;")
L.append("      end;")
L.append("    end;")
L.append("  end;")
L.append("")
L.append("  // 2) 备份英文原版")
L.append("  if not DirExists(ExpandConstant('{app}\\Hanhua\\Backup-English')) then")
L.append("    ForceDirectories(ExpandConstant('{app}\\Hanhua\\Backup-English'));")
for f in dll_files:
    src = LIB + '\\' + f if f != 'BCCPlus.dll' else CONT + '\\' + f
    bak = "{app}\\Hanhua\\Backup-English\\" + f
    L.append(f"  BackupOne('{src}', ExpandConstant('{bak}'));")
L.append("  if not DirExists(ExpandConstant('{app}\\Hanhua\\Backup-English\\aex')) then")
L.append("    ForceDirectories(ExpandConstant('{app}\\Hanhua\\Backup-English\\aex'));")
for f in aex_files:
    L.append(f"  BackupOne(CONT + '\\{f}', ExpandConstant('{{app}}\\Hanhua\\Backup-English\\aex\\{f}'));")
L.append("end;")
L.append("")
L.append("procedure CurStepChanged(CurStep: TSetupStep);")
L.append("begin")
L.append("  if CurStep = ssPostInstall then begin")
L.append("    // 让 Restore-English.bat 指向真正的备份目录")
L.append("  end;")
L.append("end;")
L.append("")

open(os.path.join(PKG, 'installer.iss'), 'w', encoding='utf-8-sig').write("\n".join(L))
print("iss 行数:", len(L))
print("aex:", len(aex_files), "dll:", len(dll_files))
