# -*- coding: utf-8 -*-
"""Human-curated Chinese names for BorisFX Continuum 2026 (BCC).

Why this file exists: the earlier "morpheme composition" pass produced
machine-translation-looking output and left 199/488 effect names with English
fragments (Colorize, Checker, Comet, DVE ...). Every string here is written by
hand so it reads like a real Chinese plugin menu.

Encoding is UTF-8 — this was verified empirically against AE 25.1 on Windows:
AE stores its own zh_CN strings as UTF-8 (``Support Files\\zstring\\zh_CN\\
localizabledictionary.dat`` starts with an EF BB BF BOM) and both
``PresetEffects.xml`` and Continuum's own ``resources\\presets\\*.xml`` declare
``encoding="utf-8"``. Writing GBK into the PiPL records makes AE answer with
"this effect could not be initialized" on every add-to-timeline.

Budget consequences: UTF-8 costs 3 bytes per CJK char (GBK costs 2), so a few
tight records no longer fit. Keep the English text there rather than truncating
mid-character.
"""

# ---------------------------------------------------------------- categories
# PiPL 'gtac' record. Budget = record size - 2. "BCC" (3 bytes) is kept
# because it is the folder name users scan for in the Effects menu.
CATS = {
    "BCC Obsolete":           "BCC旧版",
    "BCC Transitions":        "BCC转场",
    "BCC Color & Tone":       "BCC色彩影调",
    "BCC Key & Blend":        "BCC键控混合",
    "BCC Lights":             "BCC灯光",
    "BCC Stylize":            "BCC风格化",
    "BCC Art Looks":          "BCC艺术外观",
    "BCC Film Style":         "BCC胶片风格",
    "BCC Image Restoration":  "BCC图像修复",
    "BCC Warp":               "BCC扭曲",
    "BCC Grads & Tints":      "BCC渐变色调",
    "BCC Blur":               "BCC模糊",
    "BCC Optical Diffusion":  "BCC光学漫射",
    "BCC Time":               "BCC时间",
    "BCC Perspective":        "BCC透视",
    "BCC Particles":          "BCC粒子",
    "BCC 3D Objects":         "BCC三维物体",
    "BCC Lens":               "BCC镜头",
    "BCC VR":                 "BCC VR",       # only 6 bytes available; VR is standard in Chinese too
    "BCC Textures":           "BCC纹理",
    "BCC Match Move":         "BCC运动匹配",
    "BCC Browser":            "BCC浏览器",
}

# ---------------------------------------------------------------- effect names
# Key   = exact PiPL 'eman' text, stripped of the leading space.
# Value = Chinese name WITHOUT the BCC/BCC+ prefix (AE already groups them).
NAMES = {
    # ---- legacy BCC (space-prefixed) ----
    "BCC 2D Particles": "二维粒子",
    "BCC 3 Way Color Grade": "三路调色",
    "BCC 3D Extruded Image Shatter": "三维挤出图像碎裂",
    "BCC 3D Image Shatter": "三维图像碎裂",
    "BCC Alpha Pixel Noise OBS": "阿尔法像素噪点旧版",
    "BCC Alpha Process": "阿尔法通道处理",
    "BCC Alpha Spotlight OBS": "阿尔法聚光灯旧版",
    "BCC Artist's Poster": "艺术海报",
    "BCC Beat Reactor": "节拍反应器",
    "BCC Beauty Studio OBSOLETE": "美颜工作室旧版",
    "BCC Blobs Wipe": "斑点擦除",
    "BCC Blur": "模糊",
    "BCC Blur Dissolve OBSOLETE": "模糊溶解旧版",
    "BCC Boost Blend OBS": "增强混合旧版",
    "BCC Brick OBSOLETE": "砖墙旧版",
    "BCC Brightness-Contrast": "亮度对比度",
    "BCC Broadcast Safe": "广播安全",
    "BCC Bulge": "凸出",
    "BCC Bump Map": "凹凸贴图",
    "BCC Burnt Film": "灼烧胶片",
    "BCC Cartoon Look": "卡通外观",
    "BCC Cartooner": "卡通化",
    "BCC Cast Shadow": "投射阴影",
    "BCC Caustics": "焦散",
    "BCC Charcoal Sketch": "炭笔素描",
    "BCC Checker Wipe": "棋盘擦除",
    "BCC Chroma Key": "色度键控",
    "BCC Chroma Key Studio": "色度键控工作室",
    "BCC Cloth OBSOLETE": "布料旧版",
    "BCC Clouds OBSOLETE": "云层旧版",
    "BCC Color Balance": "色彩平衡",
    "BCC Color Choker": "色彩收缩",
    "BCC Color Correction": "色彩校正",
    "BCC Color Match": "色彩匹配",
    "BCC Color Palette OBS": "调色板旧版",
    "BCC Colorize": "着色",
    "BCC Colorize Glow": "着色辉光",
    "BCC Colorize Glow Dissolve": "着色辉光溶解",
    "BCC Comet OBSOLETE": "彗星旧版",
    "BCC Composite": "合成",
    "BCC Composite Choker": "合成收缩",
    "BCC Composite Dissolve": "合成溶解",
    "BCC Corner Pin OBS": "边角定位旧版",
    "BCC Corner Pin Studio": "边角定位工作室",
    "BCC Correct Selected Color": "校正所选颜色",
    "BCC Crash Zoom Dissolve OBSOLETE": "急速变焦溶解旧版",
    "BCC Criss-Cross Wipe": "十字交叉擦除",
    "BCC Cross Glitch OBSOLETE": "交叉故障旧版",
    "BCC Cross Melt": "交叉融解",
    "BCC Cross Zoom OBSOLETE": "交叉变焦旧版",
    "BCC Cube": "立方体",
    "BCC Curl": "卷曲",
    "BCC Curl Dissolve": "卷曲溶解",
    "BCC Cylinder": "圆柱体",
    "BCC DV Fixer OBSOLETE": "DV修复旧版",
    "BCC DVE Basic OBSOLETE": "DVE基础旧版",
    "BCC DVE OBSOLETE": "DVE旧版",
    "BCC Damaged TV": "电视损坏",
    "BCC Damaged TV Dissolve": "电视损坏溶解",
    "BCC DeGrain OBS": "去颗粒旧版",
    "BCC DeNoise OBS": "降噪旧版",
    "BCC Deinterlace": "去隔行",
    "BCC Directional Blur OBSOLETE": "方向模糊旧版",
    "BCC Displacement Map": "置换贴图",
    "BCC Drop Shadow": "投影",
    "BCC Dropout Fixer": "掉帧修复",
    "BCC Dust and Scratches": "灰尘与划痕",
    "BCC Edge Cleaner OBSOLETE": "边缘清理旧版",
    "BCC Edge Grunge": "边缘做旧",
    "BCC Edge Lighting": "边缘打光",
    "BCC Emboss": "浮雕",
    "BCC Extruded EPS": "EPS挤出",
    "BCC Extruded Spline": "挤出样条",
    "BCC Extruded Text": "挤出文字",
    "BCC FX Browser": "特效浏览",
    "BCC Fast Film Glow Dissolve OBSOLETE": "快速胶片辉光溶解旧版",
    "BCC Fast Film Glow OBSOLETE": "快速胶片辉光旧版",
    "BCC Fast Film Process OBSOLETE": "快速胶片处理旧版",
    "BCC Fast Flipper": "快速翻转",
    "BCC Fast Lens Blur OBSOLETE": "快速镜头模糊旧版",
    "BCC Film Damage OBSOLETE": "胶片损伤旧版",
    "BCC Film Glow Dissolve OBS": "胶片辉光溶解旧版",
    "BCC Film Glow OBS": "胶片辉光旧版",
    "BCC Film Grain OBSOLETE": "胶片颗粒旧版",
    "BCC Film Process OBS": "胶片处理旧版",
    "BCC Fire OBS": "火焰旧版",
    "BCC Flicker Fixer": "闪烁修复",
    "BCC Flutter Cut OBSOLETE": "颤动剪辑旧版",
    "BCC Fractal Noise OBSOLETE": "分形噪点旧版",
    "BCC Gaussian Blur OBSOLETE": "高斯模糊旧版",
    "BCC Glare OBSOLETE": "眩光旧版",
    "BCC Glint OBSOLETE": "微光旧版",
    "BCC Glitter OBSOLETE": "闪光旧版",
    "BCC Glow Alpha Edges": "辉光阿尔法边缘",
    "BCC Glow Matte OBS": "辉光遮罩旧版",
    "BCC Glow OBS": "辉光旧版",
    "BCC Granite OBSOLETE": "花岗岩旧版",
    "BCC Grid Wipe": "网格擦除",
    "BCC Grunge": "做旧纹理",
    "BCC Halftone": "半色调",
    "BCC Hue-Sat-Lightness": "色相饱和明度",
    "BCC Invert Solarize": "反相中途曝光",
    "BCC Jitter": "抖动",
    "BCC Jitter Basic": "抖动基础版",
    "BCC Kaleida Dissolve": "万花筒溶解",
    "BCC LED OBSOLETE": "LED旧版",
    "BCC Laser Beam": "激光束",
    "BCC Layer Deformer": "图层变形",
    "BCC Lens Blur Dissolve": "镜头模糊溶解",
    "BCC Lens Blur OBS": "镜头模糊旧版",
    "BCC Lens Correction": "镜头校正",
    "BCC Lens Distortion Wipe": "镜头畸变擦除",
    "BCC Lens Flare 3D": "三维镜头光晕",
    "BCC Lens Flare Adv OBS": "高级镜头光晕旧版",
    "BCC Lens Flare Dissolve": "镜头光晕溶解",
    "BCC Lens Flare OBS": "镜头光晕旧版",
    "BCC Lens Flare Round": "圆形镜头光晕",
    "BCC Lens Flare Spiked": "星芒镜头光晕",
    "BCC Lens Flash": "镜头闪光",
    "BCC Lens Shape": "光斑形状",
    "BCC Lens Transition OBS": "镜头转场旧版",
    "BCC Levels Gamma": "色阶伽马",
    "BCC Light Leaks Dissolve OBSOLETE": "漏光溶解旧版",
    "BCC Light Leaks OBSOLETE": "漏光旧版",
    "BCC Light Matte OBS": "亮度遮罩旧版",
    "BCC Light Sweep": "光线扫过",
    "BCC Light Wipe": "光线擦除",
    "BCC Light Wrap OBSOLETE": "光线融合旧版",
    "BCC Light Zoom OBS": "光线缩放旧版",
    "BCC Lightning": "闪电",
    "BCC Linear Color Key OBSOLETE": "线性色度键旧版",
    "BCC Linear Luma Key OBSOLETE": "线性亮度键旧版",
    "BCC Linear Wipe OBSOLETE": "线性擦除旧版",
    "BCC Looper": "循环",
    "BCC Magic Sharp OBSOLETE": "魔力锐化旧版",
    "BCC Make Alpha Key": "生成阿尔法遮罩",
    "BCC Match Grain": "颗粒匹配",
    "BCC Match Move": "运动匹配",
    "BCC Matte Choker": "遮罩收缩",
    "BCC Matte Cleanup": "遮罩清理",
    "BCC Median": "中值",
    "BCC Misalignment": "通道错位",
    "BCC Mixed Colors": "混合颜色",
    "BCC Morph": "变形",
    "BCC Mosaic OBSOLETE": "马赛克旧版",
    "BCC Motion Blur OBSOLETE": "运动模糊旧版",
    "BCC Motion Key OBSOLETE": "运动键控旧版",
    "BCC Multi Shadow": "多重阴影",
    "BCC Multi Stretch Wipe": "多重拉伸擦除",
    "BCC Multi Stripe Wipe": "多重条纹擦除",
    "BCC MultiTone Mix": "多色调混合",
    "BCC Noise Map 2": "噪点贴图2",
    "BCC Noise Map OBS": "噪点贴图旧版",
    "BCC Noise Reduction OBSOLETE": "降噪旧版",
    "BCC Optical Flow OBSOLETE": "光流法旧版",
    "BCC Optical Stabilizer": "光学防抖",
    "BCC Organic Strands": "有机丝线",
    "BCC Page Turn": "翻页",
    "BCC Pan and Zoom": "平移缩放",
    "BCC Particle Array 3D": "三维粒子阵列",
    "BCC Particle Emitter 3D": "三维粒子发射器",
    "BCC Particle Illusion": "粒子幻影",
    "BCC Particle Illusion Dissolve": "粒子幻影溶解",
    "BCC Particle System OBSOLETE": "粒子系统旧版",
    "BCC Pencil Sketch": "铅笔素描",
    "BCC Pin Art 3D": "三维图钉艺术",
    "BCC Pixel Chooser OBSOLETE": "像素选取旧版",
    "BCC Pixel Fixer": "像素修复",
    "BCC Polar Displacement": "极坐标置换",
    "BCC Posterize": "色调分离",
    "BCC Posterize Time": "时间抽帧",
    "BCC Premult": "预乘",
    "BCC Primatte Studio OBSOLETE": "Primatte抠像工作室旧版",
    "BCC Prism Dissolve OBSOLETE": "棱镜溶解旧版",
    "BCC Prism OBSOLETE": "棱镜旧版",
    "BCC Pyramid Blur OBSOLETE": "金字塔模糊旧版",
    "BCC RGB Blend": "RGB混合",
    "BCC RGB Blur Dissolve OBSOLETE": "RGB模糊溶解旧版",
    "BCC RGB Displacement Dissolve": "RGB置换溶解",
    "BCC RGB Edges": "RGB边缘",
    "BCC RGB Pixel Noise": "RGB像素噪点",
    "BCC Radial Blur OBSOLETE": "径向模糊旧版",
    "BCC Radial Wipe OBSOLETE": "径向擦除旧版",
    "BCC Rain": "下雨",
    "BCC Rays Cartoon OBSOLETE": "卡通光线旧版",
    "BCC Rays Dissolve OBSOLETE": "光线溶解旧版",
    "BCC Rays OBSOLETE": "光线旧版",
    "BCC Rays Puffy": "蓬松光线",
    "BCC Rays Radiant Edges": "光芒边缘",
    "BCC Rays Radiant Spotlight OBSOLETE": "光芒聚光灯旧版",
    "BCC Rays Ring OBSOLETE": "环形光线旧版",
    "BCC Rays Ripply OBSOLETE": "波纹光线旧版",
    "BCC Rays Streaky OBSOLETE": "条纹光线旧版",
    "BCC Rays Textured OBSOLETE": "纹理光线旧版",
    "BCC Rays Wedge OBSOLETE": "楔形光线旧版",
    "BCC Rectangular Wipe OBSOLETE": "矩形擦除旧版",
    "BCC Reflection": "反射",
    "BCC Reframer": "重构图",
    "BCC Remover": "物体移除",
    "BCC Reptilian OBSOLETE": "鳞片纹理旧版",
    "BCC Reverse Spotlight": "反向聚光灯",
    "BCC Ribbon Wipe": "缎带擦除",
    "BCC Rings Wipe": "圆环擦除",
    "BCC Ripple": "涟漪",
    "BCC Ripple Dissolve": "涟漪溶解",
    "BCC Rock OBSOLETE": "岩石旧版",
    "BCC Rough Glow OBS": "粗糙辉光旧版",
    "BCC Safe Colors OBS": "安全色旧版",
    "BCC Scanline OBSOLETE": "扫描线旧版",
    "BCC Scatterize": "散点化",
    "BCC Sequencer OBS": "序列器旧版",
    "BCC Smooth Tone OBS": "平滑色调旧版",
    "BCC Snow": "下雪",
    "BCC Sparks OBSOLETE": "火花旧版",
    "BCC Sphere": "球体",
    "BCC Sphere Transition": "球体转场",
    "BCC Spill Remover OBSOLETE": "溢色去除旧版",
    "BCC Spin Blur Dissolve OBSOLETE": "旋转模糊溶解旧版",
    "BCC Spiral Blur OBSOLETE": "螺旋模糊旧版",
    "BCC Spotlight": "聚光灯",
    "BCC Spray Paint Noise": "喷漆噪点",
    "BCC Stage Light": "舞台灯光",
    "BCC Star Matte OBS": "星形遮罩旧版",
    "BCC Stars OBSOLETE": "星光旧版",
    "BCC Steel Plate OBSOLETE": "钢板旧版",
    "BCC Super Blend OBS": "超级混合旧版",
    "BCC Swish Pan OBSOLETE": "快速摇摄旧版",
    "BCC Temporal Blur": "时域模糊",
    "BCC Textured Wipe OBSOLETE": "纹理擦除旧版",
    "BCC Tile Mosaic": "平铺马赛克",
    "BCC Tile Wipe": "平铺擦除",
    "BCC Time Displacement": "时间置换",
    "BCC Title Studio": "字幕工作室",
    "BCC Trails": "拖尾",
    "BCC Trails Basic": "拖尾基础版",
    "BCC Tritone": "三色调",
    "BCC Tritone Dissolve": "三色调溶解",
    "BCC Turbulence": "湍流",
    "BCC Twirl": "旋涡",
    "BCC Twister": "扭曲器",
    "BCC Two Strip Color OBSOLETE": "双色带调色旧版",
    "BCC Two Way Key OBSOLETE": "双向键控旧版",
    "BCC Type On Text": "打字机文字",
    "BCC Unsharp Mask": "非锐化蒙版",
    "BCC UpRez OBSOLETE": "提升分辨率旧版",
    "BCC VR Blur": "VR模糊",
    "BCC VR Flicker Fixer": "VR闪烁修复",
    "BCC VR Insert": "VR插入",
    "BCC VR Reorient": "VR重定向",
    "BCC VR Sharpen": "VR锐化",
    "BCC Vector Blur Dissolve": "矢量模糊溶解",
    "BCC Vector Displacement": "矢量置换",
    "BCC Veined Marble OBSOLETE": "纹理大理石旧版",
    "BCC Velocity Remap OBSOLETE": "速度重映射旧版",
    "BCC Video Glitch OBSOLETE": "视频故障旧版",
    "BCC Video Morph": "视频变形",
    "BCC Videoscope": "视频示波器",
    "BCC Vignette OBSOLETE": "暗角旧版",
    "BCC Vignette Wipe OBSOLETE": "暗角擦除旧版",
    "BCC Warp": "扭曲",
    "BCC Water Color": "水彩",
    "BCC Water Waves Dissolve": "水波溶解",
    "BCC Wave": "波浪",
    "BCC Weave OBSOLETE": "编织旧版",
    "BCC Wild Cards": "扑克牌",
    "BCC Wire Remover": "钢丝移除",
    "BCC WitnessProtection OBSOLETE": "证人保护旧版",
    "BCC Wood Grain OBSOLETE": "木纹旧版",
    "BCC Wooden Planks OBSOLETE": "木板旧版",
    "BCC Z Space I OBS": "Z空间I旧版",
    "BCC Z Space II OBS": "Z空间II旧版",
    "BCC Z Space III OBS": "Z空间III旧版",
    "BCC Z-Blur": "Z通道模糊",

    # ---- modern BCC+ ----
    "BCC+Ambient Light": "环境光",
    "BCC+Atmospheric Glow": "大气辉光",
    "BCC+Atmospheric Glow Dissolve": "大气辉光溶解",
    "BCC+Audio Visualizer": "音频可视化",
    "BCC+Beauty Studio": "美颜工作室",
    "BCC+Black and White": "黑白",
    "BCC+Bleach Bypass": "漂白旁路",
    "BCC+Blur": "模糊",
    "BCC+Blur Dissolve": "模糊溶解",
    "BCC+Borders": "边框",
    "BCC+Camera Shake": "镜头抖动",
    "BCC+Camera Shake Dissolve": "镜头抖动溶解",
    "BCC+Center Spot": "中心聚光",
    "BCC+Channel Blur": "通道模糊",
    "BCC+Channel Blur Dissolve": "通道模糊溶解",
    "BCC+Channel Blur YUV": "通道模糊YUV",
    "BCC+Chroma Bands": "色度条带",
    "BCC+Chromatic Aberration": "色差",
    "BCC+Color Gradient": "色彩渐变",
    "BCC+Color Infrared": "彩色红外",
    "BCC+Color Link": "色彩链接",
    "BCC+Color Paste": "色彩粘贴",
    "BCC+Color Shadow": "色彩阴影",
    "BCC+Color Spot": "色彩聚光",
    "BCC+Colorize Gradient": "着色渐变",
    "BCC+Composite": "合成",
    "BCC+Crash Zoom Dissolve": "急速变焦溶解",
    "BCC+Cross Processing": "交叉冲洗",
    "BCC+Cross Zoom Dissolve": "交叉变焦溶解",
    "BCC+Day for Night": "日夜转换",
    "BCC+DeBand": "去色带",
    "BCC+DeBlock": "去块效应",
    "BCC+DeFog": "去雾",
    "BCC+DeFringe": "去边缘色",
    "BCC+DeNoise ML": "智能降噪",
    "BCC+Depth Map ML": "智能深度贴图",
    "BCC+Depth Wipe ML": "智能深度擦除",
    "BCC+Depth of Field": "景深",
    "BCC+Detail": "细节",
    "BCC+Develop": "显影",
    "BCC+Diffusion": "柔光扩散",
    "BCC+Directional Blur": "方向模糊",
    "BCC+Directional Blur Dissolve": "方向模糊溶解",
    "BCC+Dissolve": "溶解",
    "BCC+Double Fog": "双重雾",
    "BCC+Dual Gradient": "双向渐变",
    "BCC+Edge Cleaner": "边缘清理",
    "BCC+Edge Composite": "边缘合成",
    "BCC+Enhancing": "增强",
    "BCC+Eye Light": "眼神光",
    "BCC+F-Stop": "光圈",
    "BCC+Face ML": "智能人脸",
    "BCC+Film Glow": "胶片辉光",
    "BCC+Film Glow Dissolve": "胶片辉光溶解",
    "BCC+Film Grunge": "胶片做旧",
    "BCC+Film Roll": "胶片卷动",
    "BCC+Film Stocks": "胶片类型",
    "BCC+Flashing": "闪光",
    "BCC+Fluorescent": "荧光灯",
    "BCC+Flutter Cut": "颤动剪辑",
    "BCC+Fog": "雾气",
    "BCC+Frame Fixer ML": "智能帧修复",
    "BCC+Frost": "霜冻",
    "BCC+Gels": "灯光色片",
    "BCC+Glow": "辉光",
    "BCC+Glow Darks": "暗部辉光",
    "BCC+Glow Edges": "边缘辉光",
    "BCC+Grade": "调色",
    "BCC+Grain": "颗粒",
    "BCC+Halo": "光晕",
    "BCC+Harris Shutter": "哈里斯快门",
    "BCC+Haze": "雾霾",
    "BCC+High Contrast": "高对比度",
    "BCC+Holdout Composite": "遮挡合成",
    "BCC+Ice Halos": "冰晕",
    "BCC+Infrared": "红外",
    "BCC+Jump Cut Fixer ML": "智能跳切修复",
    "BCC+Kelvin": "色温",
    "BCC+Key Light": "主光",
    "BCC+Lens Blur": "镜头模糊",
    "BCC+Lens Distortion": "镜头畸变",
    "BCC+Lens Flare": "镜头光晕",
    "BCC+License Plate ML": "智能车牌",
    "BCC+Light": "灯光",
    "BCC+Light Flicker": "灯光闪烁",
    "BCC+Light Leaks": "漏光",
    "BCC+Light Leaks Dissolve": "漏光溶解",
    "BCC+Light Wrap": "光线融合",
    "BCC+Linear Color Key": "线性色度键",
    "BCC+Linear Luma Key": "线性亮度键",
    "BCC+Linear Wipe": "线性擦除",
    "BCC+Looks": "影调",
    "BCC+Low Contrast": "低对比度",
    "BCC+Magic Sharp": "魔力锐化",
    "BCC+Math Composite": "数学合成",
    "BCC+Matte Refine ML": "智能遮罩细化",
    "BCC+Mist": "薄雾",
    "BCC+Mosaic": "马赛克",
    "BCC+Mosaic Dissolve": "马赛克溶解",
    "BCC+Motion Blur ML": "智能运动模糊",
    "BCC+Multi-Star": "多角星",
    "BCC+Multi-Star Dissolve": "多角星溶解",
    "BCC+ND Gradient": "中灰渐变",
    "BCC+Net": "网纱",
    "BCC+Night Vision": "夜视",
    "BCC+Non-Additive Mix": "非叠加混合",
    "BCC+Optical Dissolve": "光学溶解",
    "BCC+Orbs": "光球",
    "BCC+Orbs Dissolve": "光球溶解",
    "BCC+Overexpose": "过曝",
    "BCC+Photographic": "摄影风格",
    "BCC+Pixel Chooser": "像素选取",
    "BCC+Polar Warp": "极坐标扭曲",
    "BCC+Polarizer": "偏振镜",
    "BCC+Primatte Studio": "Primatte抠像工作室",
    "BCC+Prism": "棱镜",
    "BCC+Prism Dissolve": "棱镜溶解",
    "BCC+Rack Focus": "移焦",
    "BCC+Rack Focus Dissolve": "移焦溶解",
    "BCC+Radial Blur": "径向模糊",
    "BCC+Radial Exposure": "径向曝光",
    "BCC+Radial Tint": "径向染色",
    "BCC+Radial Wipe": "径向擦除",
    "BCC+Rays": "光线",
    "BCC+Rays Dissolve": "光线溶解",
    "BCC+ReLight": "重新打光",
    "BCC+Rectangular Wipe": "矩形擦除",
    "BCC+Reflector": "反光板",
    "BCC+Retimer ML": "智能变速",
    "BCC+ST Map": "ST贴图",
    "BCC+Scanline": "扫描线",
    "BCC+Selective Saturation": "选择性饱和度",
    "BCC+Sepia": "棕褐色调",
    "BCC+Shadows/Highlights": "阴影高光",
    "BCC+Silk": "柔纱",
    "BCC+Skin Tone": "肤色",
    "BCC+Smear Blur": "涂抹模糊",
    "BCC+Smoke Wipe": "烟雾擦除",
    "BCC+Smoke and Fog": "烟雾效果",
    "BCC+Smoke and Fog Dissolve": "烟雾效果溶解",
    "BCC+Spill Remover": "溢色去除",
    "BCC+Spin Blur Dissolve": "旋转模糊溶解",
    "BCC+Split Field": "分场镜",
    "BCC+Split Tone": "分离色调",
    "BCC+Streaks": "条纹光",
    "BCC+Sunset": "日落",
    "BCC+Super LED": "超级LED",
    "BCC+Swish Glow": "甩镜辉光",
    "BCC+Swish Pan": "甩镜",
    "BCC+Swish Prism": "甩镜棱镜",
    "BCC+Swish Warp": "甩镜扭曲",
    "BCC+Texture Wipe": "纹理擦除",
    "BCC+Textures": "纹理",
    "BCC+Three Strip": "三色带",
    "BCC+Tint": "染色",
    "BCC+Transform": "变换",
    "BCC+Two Strip": "双色带",
    "BCC+Two Way Key": "双向键控",
    "BCC+UpRes ML": "智能放大",
    "BCC+Video Glitch": "视频故障",
    "BCC+Video Glitch Dissolve": "视频故障溶解",
    "BCC+Vignette": "暗角",
    "BCC+Vignette Wipe": "暗角擦除",
    "BCC+Wide Angle Lens": "广角镜头",
    "BCC+Witness Protection ML": "智能证人保护",
    "BCC+X-Ray": "X光",
}

# Words that are correctly left in Latin - do NOT warn about these.
KEEP_LATIN = {
    "RGB", "YUV", "LED", "VR", "DV", "DVE", "EPS", "ML", "ST", "ND",
    "Cb", "Cr", "IRE", "FOV", "ROI", "ZIP", "ZSP", "SW", "XY", "X", "Y", "Z",
    "S", "L", "B", "C", "A", "KF", "AB", "TV", "2D", "3D", "I", "II", "III",
    "Primatte", "OBSOLETE", "OBS",
}

# ------------------------------------------------------------ short variants
# UTF-8 costs 3 bytes per CJK char, and the PiPL 'eman' record has a fixed
# length. 75 of the 488 records cannot hold the full translation above, so
# these are hand-written *shorter* forms used only when the full text does not
# fit. Keys are the same English 'eman' text as NAMES.
# Where the original already carries a status suffix the suffix is the first
# thing to drop: "旧版" is secondary information, the effect name is not.
SHORT = {
    "BCC Alpha Pixel Noise OBS":      "阿尔法噪点旧版",
    "BCC Alpha Process":              "阿尔法处理",
    "BCC Alpha Spotlight OBS":        "阿尔法聚光旧版",
    "BCC Blobs Wipe":                 "斑点擦除",
    "BCC Boost Blend OBS":            "增强混合旧版",
    "BCC Bump Map":                   "凹凸贴图",
    "BCC Burnt Film":                 "灼烧胶片",
    "BCC Chroma Key":                 "色键",
    "BCC Chroma Key Studio":          "色度键控室",
    "BCC Corner Pin OBS":             "边角钉旧版",
    "BCC Corner Pin Studio":          "边角钉工作室",
    "BCC Cross Melt":                 "交叉融解",
    "BCC Cube":                       "立方",
    "BCC Damaged TV":                 "电视损坏",
    "BCC DeNoise OBS":                "降噪旧版",
    "BCC DeGrain OBS":                "去粒旧版",
    "BCC FX Browser":                 "特效浏览",
    "BCC Film Glow OBS":              "胶片辉光旧版",
    "BCC Film Glow Dissolve OBS":     "胶片辉光溶解",
    "BCC Fire OBS":                   "火焰旧版",
    "BCC Glow OBS":                   "辉光旧版",
    "BCC Glow Alpha Edges":           "α边缘辉光",
    "BCC Glow Matte OBS":             "辉光遮罩旧版",
    "BCC Grid Wipe":                  "网格擦除",
    "BCC Grunge":                     "做旧",
    "BCC Invert Solarize":            "反相曝光",
    "BCC Jitter Basic":               "抖动基础",
    "BCC Lens Blur OBS":              "镜头模糊旧版",
    "BCC Lens Flare Adv OBS":         "高级光晕旧版",
    "BCC Lens Flare 3D":              "三维光晕",
    "BCC Lens Flash":                 "镜头闪光",
    "BCC Lens Shape":                 "光斑形状",
    "BCC Light Matte OBS":            "亮度遮罩旧版",
    "BCC Light Sweep":                "光线扫过",
    "BCC Light Wipe":                 "光线擦除",
    "BCC Light Zoom OBS":             "光线缩放旧版",
    "BCC Make Alpha Key":             "生成α遮罩",
    "BCC Match Move":                 "运动匹配",
    "BCC MultiTone Mix":              "多色调混合",
    "BCC Noise Map OBS":              "噪点图旧版",
    "BCC Noise Map 2":                "噪点贴图2",
    "BCC Posterize":                  "色调分离",
    "BCC Primatte Studio OBSOLETE":   "Primatte工作室旧版",
    "BCC Rays Puffy":                 "蓬松光",
    "BCC RGB Pixel Noise":            "RGB噪点",
    "BCC Remover":                    "物体移除",
    "BCC Rings Wipe":                 "圆环擦除",
    "BCC Rough Glow OBS":             "粗糙辉光旧版",
    "BCC Sequencer OBS":              "序列器旧版",
    "BCC Lens Flare OBS":             "镜头光晕旧版",
    "BCC Star Matte OBS":             "星形遮罩旧版",
    "BCC Super Blend OBS":            "超级混合旧版",
    "BCC Tile Mosaic":                "马赛克",
    "BCC Tile Wipe":                  "平铺擦除",
    "BCC Trails Basic":               "拖尾基础",
    "BCC Tritone":                    "三色调",
    "BCC Unsharp Mask":               "非锐化蒙版",
    "BCC UpRez OBSOLETE":             "提分辨率旧版",
    "BCC Videoscope":                 "示波器",
    "BCC Z-Blur":                     "Z模糊",
    "BCC Z Space II OBS":             "Z空间Ⅱ旧版",
    "BCC Z Space III OBS":            "Z空间Ⅲ旧版",
    "BCC+Gels":                       "色片",
    "BCC+Polar Warp":                 "极坐标",
    "BCC+Primatte Studio":            "Primatte工作室",
    "BCC+Sepia":                      "棕褐调",
}
